version: '3.8'

services:
  dev:
    image: 'node:22.0.0-alpine'
    command: 'npm run start:dev'
    working_dir: '/app'
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      LOAD_EXAMPLE_DATA: 'true'
    depends_on:
      - dynamodb
      - postgres
      - pgadmin
      - dynamodbadmin
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/ready']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

  dynamodb:
    image: amazon/dynamodb-local:2.3.0
    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_SESSION_TOKEN: ''
      AWS_DEFAULT_REGION: ''
      DDB_LOCAL_TELEMETRY: '0'
    ports:
      - '8000:8000'

  dynamodbadmin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb:8000'
    depends_on:
      - dynamodb

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    depends_on:
      - postgres
